# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=256)),
                ('admin_name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('verified', 'verified'), ('pending', 'pending')], default='pending', max_length=8)),
                ('docs_link', models.URLField()),
                ('error_message', models.CharField(blank=True, max_length=512, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
