# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaign.Campaign'),
        ),
    ]
