# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20170708_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
